server:
  port: 8080
  
spring:  profiles:    active:    - local

---

spring:  profiles: local
  datasource:    url: jdbc:mariadb://127.0.0.1:3306/local_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:    hibernate:      #ddl-auto: validate
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
logging:  level:    com.jpa: debug
    org.springframework.web: debug